package souldestroyer

object READ_ME_OMG {
    /*
    * THIS SOFTWARE IS HASTILY WRITTEN, PROBABLY BUGGY AND NOT AT ALL INTENDED FOR PUBLIC USE
    * (I'M SERIOUS, THE TESTING OF THIS CODE IS LACKLUSTER :P)
    *
    * IT IS PROVIDED "AS IS", WITHOUT ANY WARRANTY. THE AUTHOR IS NOT RESPONSIBLE FOR ANY
    * DAMAGES, INCLUDING FINANCIAL LOSSES OF ANY KIND, THAT STEM FROM USING THIS SOFTWARE.
    *
    * THE SHARING OF THIS SOFTWARE IS FORBIDDEN WITHOUT EXPLICIT CONSENT OF THE AUTHOR.
    * THE REASON FOR THAT IS *NOT* BECAUSE THIS IS AMAZING CODE, BUT BECAUSE IT'S PROBABLY DANGEROUS!
    *
    * */
}